# Generated by Django 5.1.2 on 2024-10-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration_info',
            name='fuel_type',
            field=models.CharField(default='DIESEL', max_length=50),
        ),
    ]
