# Generated by Django 5.1.2 on 2024-12-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_site_info_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuellevel',
            options={'permissions': [('view_restricted_data', 'Can view restricted data')]},
        ),
    ]
